# Generated by Django 4.2.3 on 2023-08-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')])),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.TextField(choices=[('ernamkulam', 'Ernamkulam'), ('thrissur', 'Thrissur'), ('kottayam', 'Kottayam'), ('alappuzha', 'Alappuzha'), ('idukki', 'Idukki')])),
                ('account_type', models.TextField(choices=[('savings', 'Savings'), ('current', 'Current')])),
                ('materials_required', models.TextField(choices=[('debit', 'Debit Card'), ('credit', 'Credit Card'), ('cheque', 'Chequebook')])),
            ],
        ),
    ]
