# Generated by Django 4.2.3 on 2023-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formss',
            name='branch',
            field=models.TextField(choices=[('aluva', 'Aluva'), ('edapally', 'edapally'), ('angamaly', 'Angamaly'), ('paravur', 'Paravur')], default=2345),
            preserve_default=False,
        ),
    ]
