# Generated by Django 4.2.3 on 2023-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0002_formss_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='formss',
            name='address',
            field=models.TextField(default=2345),
            preserve_default=False,
        ),
    ]
